### ISSUE TITLE
README.md: Deployment instructions

### ISSUE THREAD

**Issue by michael-martinez** [Vifon/qrcode-wifi#2]
Could you please provide deployment instructions ?
I am new to webpack and I am unable to deploy the project.

On webpack Getting Started tutorial (https://webpack.js.org/guides/getting-started/), I successfully ran:
$ npx webpack

On this specific project I tried:
$ npm i
$ npm run-script build and $ npx webpack 

CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no)

I am getting various errors:Error: Cannot find module 'webpack-cli'
Require stack:
- /home/michaelmartinez/.npm/_npx/14386/lib/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /home/michaelmartinez/.npm/_npx/14386/lib/node_modules/webpack/bin/webpack.js:119:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/michaelmartinez/.npm/_npx/14386/lib/node_modules/webpack/bin/webpack.js'
  ]
}

**Comment by vifon** [comment]
Hello and apologies for a long delay. It seems building this project with the current versions of the JS stack is troublesome. For a time being, you should be able to clone a pre-processed version from [the Github Pages branch](/vifon/qrcode-wifi/tree/gh-pages). It's a purely frontend application so that should be all you need.
